apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: soundilan75-ui/${{ values.repo }}
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental

